
[[override]]
  branch = "master"
  name = "github.com/mkrautz/goar"

[[override]]
  branch = "master"
  name = "github.com/smira/go-uuid"

[[override]]
  branch = "master"
  name = "github.com/smira/go-xz"

[[override]]
  name = "github.com/ugorji/go"
  revision = "71c2886f5a673a35f909803f38ece5810165097b"

[[override]]
  branch = "master"
  name = "golang.org/x/crypto"

[[override]]
  branch = "master"
  name = "golang.org/x/sys"

[[override]]
  branch = "v1"
  name = "gopkg.in/check.v1"
