language: go

go:
  - 1.2.1
  - 1.3
  - tip

env:
  global:
    - secure: "YSwtFrMqh4oUvdSQTXBXMHHLWeQgyNEL23ChIZwU0nuDGIcQZ65kipu0PzefedtUbK4ieC065YCUi4UDDh6gPotB/Wu1pnYg3dyQ7rFvhaVYAAUEpajAdXZhlx+7+J8a4FZMeC/kqiahxoRgLbthF9019ouIqhGB9zHKI6/yZwc="

install:
  - make prepare


script: make travis

matrix:
    allow_failures:
        - go: tip
